#!/bin/bash

#    bytes      file name
#----------------------------------
# 47040016 train-images-idx3-ubyte
#    60008 train-labels-idx1-ubyte
#  7840016 t10k-images-idx3-ubyte
#    10008 t10k-labels-idx1-ubyte

mkdir -p t

for t in "train" "t10k"; do
    for x in "images" "labels"; do
        [ "$x" = "images" ] && n=3 || n=1
        f="$t-$x-idx$n-ubyte"
        [ -f "$f" ] || \
            curl -o - http://yann.lecun.com/exdb/mnist/"$f".gz | gunzip > "$f"
    done
done

batch=1000
ls *-ubyte | while read f; do
    echo $f | grep -q "images" && header=16 || header=8
    echo $f | grep -q "images" && ext="bmp" || ext="lvl"
    echo $f | grep -q "images" && unit=$((28 * 28 * batch)) || unit=$((1 * batch))
    echo $f | grep -q "train" && entries=60000 || entries=10000
    max=$((entries / batch - 1))
    for i in $(seq 0 $max); do
        n=$(printf "%03d" $i)
        skip=$((header + i * unit))
        dd if="$f" of="t/$f-$n.$ext" bs=1 count="$unit" skip="$skip"
    done
done
